@EmployeesCollaborationTracker_HostAddress = http://localhost:5036

POST {{EmployeesCollaborationTracker_HostAddress}}/api/employees/collaborations
Content-Type: multipart/form-data; boundary=----EmployeesCollaborationTrackerBoundary

------EmployeesCollaborationTrackerBoundary
Content-Disposition: form-data; name="file"; filename="employees.csv"
Content-Type: text/csv

------EmployeesCollaborationTrackerBoundary--

###
